/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWellnessRouteImport } from './routes/_authenticated/wellness'
import { Route as AuthenticatedTherapistProfileRouteImport } from './routes/_authenticated/therapist-profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedTherapistsIndexRouteImport } from './routes/_authenticated/therapists/index'
import { Route as AuthenticatedDsmIndexRouteImport } from './routes/_authenticated/dsm/index'
import { Route as AuthenticatedClinicianIndexRouteImport } from './routes/_authenticated/clinician/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedWellnessInsightsRouteImport } from './routes/_authenticated/wellness.insights'
import { Route as AuthenticatedTherapistsTherapistIdRouteImport } from './routes/_authenticated/therapists/$therapistId'
import { Route as AuthenticatedDsmFavoritesRouteImport } from './routes/_authenticated/dsm/favorites'
import { Route as AuthenticatedDsmAttemptsRouteImport } from './routes/_authenticated/dsm/attempts'
import { Route as AuthenticatedDsmChapterSlugRouteImport } from './routes/_authenticated/dsm/$chapterSlug'
import { Route as AuthenticatedBookingsBookingIdRouteImport } from './routes/_authenticated/bookings/$bookingId'
import { Route as AuthenticatedDsmQuizChapterSlugRouteImport } from './routes/_authenticated/dsm/quiz.$chapterSlug'
import { Route as AuthenticatedDsmDisorderDisorderSlugRouteImport } from './routes/_authenticated/dsm/disorder.$disorderSlug'
import { Route as AuthenticatedClinicianClientsClientIdRouteImport } from './routes/_authenticated/clinician/clients.$clientId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWellnessRoute = AuthenticatedWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTherapistProfileRoute =
  AuthenticatedTherapistProfileRouteImport.update({
    id: '/therapist-profile',
    path: '/therapist-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTherapistsIndexRoute =
  AuthenticatedTherapistsIndexRouteImport.update({
    id: '/therapists/',
    path: '/therapists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDsmIndexRoute = AuthenticatedDsmIndexRouteImport.update({
  id: '/dsm/',
  path: '/dsm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClinicianIndexRoute =
  AuthenticatedClinicianIndexRouteImport.update({
    id: '/clinician/',
    path: '/clinician/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWellnessInsightsRoute =
  AuthenticatedWellnessInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedWellnessRoute,
  } as any)
const AuthenticatedTherapistsTherapistIdRoute =
  AuthenticatedTherapistsTherapistIdRouteImport.update({
    id: '/therapists/$therapistId',
    path: '/therapists/$therapistId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDsmFavoritesRoute =
  AuthenticatedDsmFavoritesRouteImport.update({
    id: '/dsm/favorites',
    path: '/dsm/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDsmAttemptsRoute =
  AuthenticatedDsmAttemptsRouteImport.update({
    id: '/dsm/attempts',
    path: '/dsm/attempts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDsmChapterSlugRoute =
  AuthenticatedDsmChapterSlugRouteImport.update({
    id: '/dsm/$chapterSlug',
    path: '/dsm/$chapterSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsBookingIdRoute =
  AuthenticatedBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDsmQuizChapterSlugRoute =
  AuthenticatedDsmQuizChapterSlugRouteImport.update({
    id: '/dsm/quiz/$chapterSlug',
    path: '/dsm/quiz/$chapterSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDsmDisorderDisorderSlugRoute =
  AuthenticatedDsmDisorderDisorderSlugRouteImport.update({
    id: '/dsm/disorder/$disorderSlug',
    path: '/dsm/disorder/$disorderSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClinicianClientsClientIdRoute =
  AuthenticatedClinicianClientsClientIdRouteImport.update({
    id: '/clinician/clients/$clientId',
    path: '/clinician/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/therapist-profile': typeof AuthenticatedTherapistProfileRoute
  '/wellness': typeof AuthenticatedWellnessRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/dsm/$chapterSlug': typeof AuthenticatedDsmChapterSlugRoute
  '/dsm/attempts': typeof AuthenticatedDsmAttemptsRoute
  '/dsm/favorites': typeof AuthenticatedDsmFavoritesRoute
  '/therapists/$therapistId': typeof AuthenticatedTherapistsTherapistIdRoute
  '/wellness/insights': typeof AuthenticatedWellnessInsightsRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/clinician/': typeof AuthenticatedClinicianIndexRoute
  '/dsm/': typeof AuthenticatedDsmIndexRoute
  '/therapists/': typeof AuthenticatedTherapistsIndexRoute
  '/clinician/clients/$clientId': typeof AuthenticatedClinicianClientsClientIdRoute
  '/dsm/disorder/$disorderSlug': typeof AuthenticatedDsmDisorderDisorderSlugRoute
  '/dsm/quiz/$chapterSlug': typeof AuthenticatedDsmQuizChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/therapist-profile': typeof AuthenticatedTherapistProfileRoute
  '/wellness': typeof AuthenticatedWellnessRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/dsm/$chapterSlug': typeof AuthenticatedDsmChapterSlugRoute
  '/dsm/attempts': typeof AuthenticatedDsmAttemptsRoute
  '/dsm/favorites': typeof AuthenticatedDsmFavoritesRoute
  '/therapists/$therapistId': typeof AuthenticatedTherapistsTherapistIdRoute
  '/wellness/insights': typeof AuthenticatedWellnessInsightsRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/clinician': typeof AuthenticatedClinicianIndexRoute
  '/dsm': typeof AuthenticatedDsmIndexRoute
  '/therapists': typeof AuthenticatedTherapistsIndexRoute
  '/clinician/clients/$clientId': typeof AuthenticatedClinicianClientsClientIdRoute
  '/dsm/disorder/$disorderSlug': typeof AuthenticatedDsmDisorderDisorderSlugRoute
  '/dsm/quiz/$chapterSlug': typeof AuthenticatedDsmQuizChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/crisis': typeof CrisisRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/therapist-profile': typeof AuthenticatedTherapistProfileRoute
  '/_authenticated/wellness': typeof AuthenticatedWellnessRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/_authenticated/dsm/$chapterSlug': typeof AuthenticatedDsmChapterSlugRoute
  '/_authenticated/dsm/attempts': typeof AuthenticatedDsmAttemptsRoute
  '/_authenticated/dsm/favorites': typeof AuthenticatedDsmFavoritesRoute
  '/_authenticated/therapists/$therapistId': typeof AuthenticatedTherapistsTherapistIdRoute
  '/_authenticated/wellness/insights': typeof AuthenticatedWellnessInsightsRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/clinician/': typeof AuthenticatedClinicianIndexRoute
  '/_authenticated/dsm/': typeof AuthenticatedDsmIndexRoute
  '/_authenticated/therapists/': typeof AuthenticatedTherapistsIndexRoute
  '/_authenticated/clinician/clients/$clientId': typeof AuthenticatedClinicianClientsClientIdRoute
  '/_authenticated/dsm/disorder/$disorderSlug': typeof AuthenticatedDsmDisorderDisorderSlugRoute
  '/_authenticated/dsm/quiz/$chapterSlug': typeof AuthenticatedDsmQuizChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crisis'
    | '/login'
    | '/signup'
    | '/assessments'
    | '/chat'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/therapist-profile'
    | '/wellness'
    | '/api/chat'
    | '/bookings/$bookingId'
    | '/dsm/$chapterSlug'
    | '/dsm/attempts'
    | '/dsm/favorites'
    | '/therapists/$therapistId'
    | '/wellness/insights'
    | '/bookings/'
    | '/clinician/'
    | '/dsm/'
    | '/therapists/'
    | '/clinician/clients/$clientId'
    | '/dsm/disorder/$disorderSlug'
    | '/dsm/quiz/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crisis'
    | '/login'
    | '/signup'
    | '/assessments'
    | '/chat'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/therapist-profile'
    | '/wellness'
    | '/api/chat'
    | '/bookings/$bookingId'
    | '/dsm/$chapterSlug'
    | '/dsm/attempts'
    | '/dsm/favorites'
    | '/therapists/$therapistId'
    | '/wellness/insights'
    | '/bookings'
    | '/clinician'
    | '/dsm'
    | '/therapists'
    | '/clinician/clients/$clientId'
    | '/dsm/disorder/$disorderSlug'
    | '/dsm/quiz/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/crisis'
    | '/login'
    | '/signup'
    | '/_authenticated/assessments'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/therapist-profile'
    | '/_authenticated/wellness'
    | '/api/chat'
    | '/_authenticated/bookings/$bookingId'
    | '/_authenticated/dsm/$chapterSlug'
    | '/_authenticated/dsm/attempts'
    | '/_authenticated/dsm/favorites'
    | '/_authenticated/therapists/$therapistId'
    | '/_authenticated/wellness/insights'
    | '/_authenticated/bookings/'
    | '/_authenticated/clinician/'
    | '/_authenticated/dsm/'
    | '/_authenticated/therapists/'
    | '/_authenticated/clinician/clients/$clientId'
    | '/_authenticated/dsm/disorder/$disorderSlug'
    | '/_authenticated/dsm/quiz/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CrisisRoute: typeof CrisisRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wellness': {
      id: '/_authenticated/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthenticatedWellnessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/therapist-profile': {
      id: '/_authenticated/therapist-profile'
      path: '/therapist-profile'
      fullPath: '/therapist-profile'
      preLoaderRoute: typeof AuthenticatedTherapistProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/therapists/': {
      id: '/_authenticated/therapists/'
      path: '/therapists'
      fullPath: '/therapists/'
      preLoaderRoute: typeof AuthenticatedTherapistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dsm/': {
      id: '/_authenticated/dsm/'
      path: '/dsm'
      fullPath: '/dsm/'
      preLoaderRoute: typeof AuthenticatedDsmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinician/': {
      id: '/_authenticated/clinician/'
      path: '/clinician'
      fullPath: '/clinician/'
      preLoaderRoute: typeof AuthenticatedClinicianIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wellness/insights': {
      id: '/_authenticated/wellness/insights'
      path: '/insights'
      fullPath: '/wellness/insights'
      preLoaderRoute: typeof AuthenticatedWellnessInsightsRouteImport
      parentRoute: typeof AuthenticatedWellnessRoute
    }
    '/_authenticated/therapists/$therapistId': {
      id: '/_authenticated/therapists/$therapistId'
      path: '/therapists/$therapistId'
      fullPath: '/therapists/$therapistId'
      preLoaderRoute: typeof AuthenticatedTherapistsTherapistIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dsm/favorites': {
      id: '/_authenticated/dsm/favorites'
      path: '/dsm/favorites'
      fullPath: '/dsm/favorites'
      preLoaderRoute: typeof AuthenticatedDsmFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dsm/attempts': {
      id: '/_authenticated/dsm/attempts'
      path: '/dsm/attempts'
      fullPath: '/dsm/attempts'
      preLoaderRoute: typeof AuthenticatedDsmAttemptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dsm/$chapterSlug': {
      id: '/_authenticated/dsm/$chapterSlug'
      path: '/dsm/$chapterSlug'
      fullPath: '/dsm/$chapterSlug'
      preLoaderRoute: typeof AuthenticatedDsmChapterSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/$bookingId': {
      id: '/_authenticated/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dsm/quiz/$chapterSlug': {
      id: '/_authenticated/dsm/quiz/$chapterSlug'
      path: '/dsm/quiz/$chapterSlug'
      fullPath: '/dsm/quiz/$chapterSlug'
      preLoaderRoute: typeof AuthenticatedDsmQuizChapterSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dsm/disorder/$disorderSlug': {
      id: '/_authenticated/dsm/disorder/$disorderSlug'
      path: '/dsm/disorder/$disorderSlug'
      fullPath: '/dsm/disorder/$disorderSlug'
      preLoaderRoute: typeof AuthenticatedDsmDisorderDisorderSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinician/clients/$clientId': {
      id: '/_authenticated/clinician/clients/$clientId'
      path: '/clinician/clients/$clientId'
      fullPath: '/clinician/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClinicianClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedWellnessRouteChildren {
  AuthenticatedWellnessInsightsRoute: typeof AuthenticatedWellnessInsightsRoute
}

const AuthenticatedWellnessRouteChildren: AuthenticatedWellnessRouteChildren = {
  AuthenticatedWellnessInsightsRoute: AuthenticatedWellnessInsightsRoute,
}

const AuthenticatedWellnessRouteWithChildren =
  AuthenticatedWellnessRoute._addFileChildren(
    AuthenticatedWellnessRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTherapistProfileRoute: typeof AuthenticatedTherapistProfileRoute
  AuthenticatedWellnessRoute: typeof AuthenticatedWellnessRouteWithChildren
  AuthenticatedBookingsBookingIdRoute: typeof AuthenticatedBookingsBookingIdRoute
  AuthenticatedDsmChapterSlugRoute: typeof AuthenticatedDsmChapterSlugRoute
  AuthenticatedDsmAttemptsRoute: typeof AuthenticatedDsmAttemptsRoute
  AuthenticatedDsmFavoritesRoute: typeof AuthenticatedDsmFavoritesRoute
  AuthenticatedTherapistsTherapistIdRoute: typeof AuthenticatedTherapistsTherapistIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedClinicianIndexRoute: typeof AuthenticatedClinicianIndexRoute
  AuthenticatedDsmIndexRoute: typeof AuthenticatedDsmIndexRoute
  AuthenticatedTherapistsIndexRoute: typeof AuthenticatedTherapistsIndexRoute
  AuthenticatedClinicianClientsClientIdRoute: typeof AuthenticatedClinicianClientsClientIdRoute
  AuthenticatedDsmDisorderDisorderSlugRoute: typeof AuthenticatedDsmDisorderDisorderSlugRoute
  AuthenticatedDsmQuizChapterSlugRoute: typeof AuthenticatedDsmQuizChapterSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTherapistProfileRoute: AuthenticatedTherapistProfileRoute,
  AuthenticatedWellnessRoute: AuthenticatedWellnessRouteWithChildren,
  AuthenticatedBookingsBookingIdRoute: AuthenticatedBookingsBookingIdRoute,
  AuthenticatedDsmChapterSlugRoute: AuthenticatedDsmChapterSlugRoute,
  AuthenticatedDsmAttemptsRoute: AuthenticatedDsmAttemptsRoute,
  AuthenticatedDsmFavoritesRoute: AuthenticatedDsmFavoritesRoute,
  AuthenticatedTherapistsTherapistIdRoute:
    AuthenticatedTherapistsTherapistIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedClinicianIndexRoute: AuthenticatedClinicianIndexRoute,
  AuthenticatedDsmIndexRoute: AuthenticatedDsmIndexRoute,
  AuthenticatedTherapistsIndexRoute: AuthenticatedTherapistsIndexRoute,
  AuthenticatedClinicianClientsClientIdRoute:
    AuthenticatedClinicianClientsClientIdRoute,
  AuthenticatedDsmDisorderDisorderSlugRoute:
    AuthenticatedDsmDisorderDisorderSlugRoute,
  AuthenticatedDsmQuizChapterSlugRoute: AuthenticatedDsmQuizChapterSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CrisisRoute: CrisisRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
