
-- Helper: insert function-like via WITH ch as chapter lookup
-- We'll inline chapter_id subqueries per row for clarity.

INSERT INTO public.dsm_disorders
  (chapter_id, slug, name, icd10, icd11, overview, symptoms, duration_requirement,
   functional_impairment, prevalence, course, treatment_overview,
   differential_diagnoses, comorbidities, risk_factors,
   developmental_considerations, gender_considerations, cultural_considerations)
VALUES
-- ============ CHAPTER 1: NEURODEVELOPMENTAL ============
((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'global-developmental-delay', 'Global Developmental Delay', 'F88', '6A00.Z',
 'Diagnosis reserved for children under 5 who fail to meet expected developmental milestones in multiple intellectual domains and cannot be reliably assessed.',
 ARRAY['Delays in motor milestones','Delayed speech/language','Delayed adaptive functioning','Delayed social-emotional skills','Delayed cognitive processing','Requires reassessment over time'],
 'Persistent across early childhood until formal assessment is possible',
 'Significant delays affecting daily care, learning, and social interaction',
 'Estimated 1–3% of children under 5',
 'Some children catch up; others progress to intellectual developmental disorder',
 'Early intervention services, speech/OT/PT, parent training, environmental enrichment',
 ARRAY['Intellectual Developmental Disorder','Autism Spectrum Disorder','Specific Learning Disorder','Hearing/vision impairment'],
 ARRAY['Seizure disorders','Genetic syndromes','ADHD'],
 ARRAY['Prematurity','Prenatal toxin exposure','Genetic conditions','Perinatal injury'],
 'Diagnosis specific to children under 5','Slightly more common in males','Cultural norms shape milestone expectations'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'specific-learning-disorder', 'Specific Learning Disorder', 'F81.0', '6A03',
 'Persistent difficulties learning and using academic skills (reading, written expression, or mathematics) substantially below age expectations despite adequate instruction.',
 ARRAY['Inaccurate or slow word reading','Poor reading comprehension','Spelling difficulties','Problems with written expression','Trouble with number sense','Difficulty with mathematical reasoning','Avoidance of academic tasks'],
 'At least 6 months despite targeted intervention',
 'Markedly interferes with academic, occupational, or daily functioning',
 '5–15% of school-age children',
 'Chronic; impacts can persist into adulthood, especially without support',
 'Evidence-based academic remediation, classroom accommodations, assistive technology, family support',
 ARRAY['Intellectual Developmental Disorder','ADHD','Sensory impairments','Inadequate instruction'],
 ARRAY['ADHD','Anxiety','Depression','Communication disorders'],
 ARRAY['Family history','Prenatal exposure','Low birth weight','Low parental education'],
 'Emerges during school years; may surface later when demands exceed capacity','Slightly more common in males','Language and orthography influence presentation'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'language-disorder', 'Language Disorder', 'F80.2', '6A01.0',
 'Persistent difficulties in acquisition and use of language across modalities due to deficits in comprehension or production.',
 ARRAY['Reduced vocabulary','Limited sentence structure','Impaired discourse','Poor narrative skills','Difficulty following directions','Word-finding problems'],
 'Onset in early developmental period; persistent',
 'Impacts academic, social, and occupational communication',
 '~7% of children',
 'Often persists; many improve with intervention',
 'Speech-language therapy, classroom supports, parent coaching',
 ARRAY['Hearing impairment','ASD','Intellectual disability','Selective mutism'],
 ARRAY['Specific Learning Disorder','ADHD','Anxiety'],
 ARRAY['Family history','Prematurity','Recurrent otitis media'],
 'Apparent by early school years','Slight male predominance','Multilingual environments require careful assessment'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'speech-sound-disorder', 'Speech Sound Disorder', 'F80.0', '6A01.1',
 'Persistent difficulty with speech sound production that interferes with intelligibility or verbal communication.',
 ARRAY['Mispronunciation of sounds','Distortions or substitutions','Unintelligible speech','Limited phonemic inventory'],
 'Onset early childhood',
 'Affects social participation and academic performance',
 '~8–9% in young children, dropping with age',
 'Often resolves with therapy; can persist',
 'Speech-language pathology, articulation and phonological therapy',
 ARRAY['Childhood-Onset Fluency Disorder','Hearing impairment','Dysarthria'],
 ARRAY['Language Disorder','SLD'],
 ARRAY['Family history','Otitis media','Prematurity'],
 'Typical resolution before adolescence','More common in males','Dialect must be distinguished from disorder'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'childhood-onset-fluency-disorder', 'Childhood-Onset Fluency Disorder (Stuttering)', 'F80.81', '6A01.2',
 'Disturbances in normal fluency and time patterning of speech inappropriate for the individual''s age.',
 ARRAY['Sound and syllable repetitions','Sound prolongations','Broken words','Audible or silent blocking','Circumlocutions','Physical tension during speech','Monosyllabic whole-word repetitions'],
 'Onset typically ages 2–7; persistent',
 'Impacts academic and social participation, may cause anxiety',
 '~1% of children; lower in adults',
 'Often remits; ~20% persist into adulthood',
 'Speech-language therapy, fluency shaping, cognitive-behavioral support',
 ARRAY['Normal disfluencies','Tourette''s disorder','Neurogenic stuttering'],
 ARRAY['Social anxiety disorder','ADHD'],
 ARRAY['Family history','Male sex'],
 'Onset in preschool years','3–4× more common in males','Cultural attitudes affect help-seeking'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'social-pragmatic-communication-disorder', 'Social (Pragmatic) Communication Disorder', 'F80.82', '6A01.22',
 'Persistent difficulties with the social use of verbal and nonverbal communication in the absence of restricted/repetitive behaviors.',
 ARRAY['Trouble greeting/sharing information appropriately','Difficulty matching communication to context','Problems following conversation rules','Difficulty understanding inference, idioms, humor'],
 'Symptoms in early developmental period; usually diagnosed after age 4–5',
 'Limits social relationships, academic performance, and occupational function',
 'Unknown; relatively rare diagnosis',
 'Chronic with variable severity',
 'Pragmatic language therapy, social skills training, school supports',
 ARRAY['Autism Spectrum Disorder','Language Disorder','Intellectual Disability','Social Anxiety'],
 ARRAY['ADHD','Specific Learning Disorder'],
 ARRAY['Family history of communication or ASD'],
 'Diagnosed once social demands exceed capacity','Slight male predominance','Norms for social communication vary'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'developmental-coordination-disorder', 'Developmental Coordination Disorder', 'F82', '6A04',
 'Acquisition and execution of coordinated motor skills substantially below expected level, interfering with daily activities.',
 ARRAY['Clumsiness','Slowness/inaccuracy of motor performance','Difficulty with handwriting','Trouble with self-care tasks','Poor sports performance','Frequent falls or bumping into objects'],
 'Onset in early developmental period; persistent',
 'Impacts academic, leisure, and self-care activities',
 '~5–6% of children',
 'Often persists into adolescence/adulthood',
 'Occupational therapy, task-specific motor training, accommodations',
 ARRAY['Cerebral palsy','Muscular dystrophy','Visual impairment','ID'],
 ARRAY['ADHD','SLD','ASD'],
 ARRAY['Prematurity','Low birth weight','Prenatal alcohol exposure'],
 'Apparent when motor demands increase','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'stereotypic-movement-disorder', 'Stereotypic Movement Disorder', 'F98.4', '6A06',
 'Repetitive, seemingly driven, and apparently purposeless motor behavior (e.g., hand flapping, body rocking, self-biting).',
 ARRAY['Hand shaking/waving','Body rocking','Head banging','Self-biting','Skin picking','Self-hitting'],
 'Onset in early developmental period; persistent',
 'May cause physical injury or interfere with activities',
 '3–4% of children; higher with ID',
 'Variable; may diminish or persist',
 'Behavioral therapy (habit reversal, response interruption), environmental enrichment, treat injury',
 ARRAY['Tic disorders','OCD','Trichotillomania','Self-injury in ASD'],
 ARRAY['ID','ASD','Sensory impairments'],
 ARRAY['ID','Sensory deprivation','Genetic syndromes'],
 'Onset before age 3','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurodevelopmental'), 'tourettes-disorder', 'Tourette''s Disorder', 'F95.2', '8A05.00',
 'Multiple motor tics and one or more vocal tics that have been present at some time during the illness.',
 ARRAY['Multiple motor tics (eye blinking, head jerking, shoulder shrugging)','Vocal tics (throat clearing, grunting, words)','Premonitory urges','Tic suppression with later rebound'],
 'Tics for more than 1 year since first onset, before age 18',
 'Affects social interaction, schooling, self-esteem',
 '0.3–0.8% of school-age children',
 'Onset 4–6; peak severity 10–12; often improves in adolescence',
 'Psychoeducation, Comprehensive Behavioral Intervention for Tics (CBIT), alpha-agonists, antipsychotics if severe',
 ARRAY['Persistent motor/vocal tic disorder','Provisional tic disorder','Stereotypies','OCD'],
 ARRAY['ADHD','OCD','Anxiety','Learning disorders'],
 ARRAY['Family history','Perinatal complications','Streptococcal infection (PANDAS hypothesis)'],
 'Onset in childhood','3–4× more common in males','Stigma varies culturally'),

-- ============ CHAPTER 2: SCHIZOPHRENIA SPECTRUM ============
((SELECT id FROM dsm_chapters WHERE slug='schizophrenia-spectrum'), 'schizophreniform-disorder', 'Schizophreniform Disorder', 'F20.81', '6A21',
 'Symptoms identical to schizophrenia but with shorter total duration (1–6 months).',
 ARRAY['Delusions','Hallucinations','Disorganized speech','Grossly disorganized or catatonic behavior','Negative symptoms'],
 'At least 1 month, less than 6 months',
 'Often significant impairment, though some recover fully',
 '~0.2% lifetime',
 '~one-third recover; two-thirds progress to schizophrenia or schizoaffective',
 'Antipsychotics, supportive psychotherapy, family involvement, early intervention services',
 ARRAY['Schizophrenia','Brief Psychotic Disorder','Bipolar with psychotic features','Substance-induced psychosis'],
 ARRAY['Substance use','Depression','Anxiety'],
 ARRAY['Family history','Cannabis use','Prenatal complications'],
 'Typically late adolescence/early adulthood','Equal across sexes','Stigma and idioms of distress shape presentation'),

((SELECT id FROM dsm_chapters WHERE slug='schizophrenia-spectrum'), 'delusional-disorder', 'Delusional Disorder', 'F22', '6A24',
 'Presence of one or more delusions for at least 1 month without other prominent psychotic symptoms; functioning is not markedly impaired apart from the delusion.',
 ARRAY['Non-bizarre or bizarre delusions (erotomanic, grandiose, jealous, persecutory, somatic, mixed)','Behavior consistent with delusion','Preserved general functioning','Absence of prominent hallucinations'],
 '1 month or longer',
 'Variable; can be circumscribed to delusional themes',
 '~0.2% lifetime',
 'Often chronic with fluctuating intensity',
 'Antipsychotics, CBT for psychosis, building therapeutic alliance',
 ARRAY['Schizophrenia','OCD with poor insight','Body dysmorphic disorder','Personality disorders'],
 ARRAY['Depression','Substance use'],
 ARRAY['Older age','Sensory impairment','Immigration/social isolation'],
 'Onset in middle/late adulthood','Slight female predominance','Cultural beliefs must be distinguished from delusions'),

((SELECT id FROM dsm_chapters WHERE slug='schizophrenia-spectrum'), 'catatonia', 'Catatonia (Associated with Another Mental Disorder)', 'F06.1', '6A40',
 'Marked psychomotor disturbance involving decreased motor activity, decreased engagement, or excessive/peculiar motor activity.',
 ARRAY['Stupor','Catalepsy','Waxy flexibility','Mutism','Negativism','Posturing','Mannerisms','Stereotypies','Agitation','Grimacing','Echolalia','Echopraxia'],
 'Episodic; can last hours to weeks',
 'Severe; medical emergency if untreated',
 'Up to 10% of acute psychiatric admissions',
 'Variable; responsive to benzodiazepines/ECT',
 'Benzodiazepines (lorazepam challenge), ECT, treat underlying disorder, supportive care',
 ARRAY['NMS','Malignant hyperthermia','Locked-in syndrome','Stiff-person syndrome'],
 ARRAY['Mood disorders','Schizophrenia','Autism','Medical conditions'],
 ARRAY['Mood/psychotic illness','Medical illness','Antipsychotic exposure'],
 '—','Equal across sexes','—'),

-- ============ CHAPTER 4: DEPRESSIVE ============
((SELECT id FROM dsm_chapters WHERE slug='depressive'), 'disruptive-mood-dysregulation-disorder', 'Disruptive Mood Dysregulation Disorder', 'F34.81', '6A72',
 'Severe recurrent temper outbursts grossly out of proportion to situation, with persistent irritable/angry mood between outbursts in children.',
 ARRAY['Severe verbal/behavioral temper outbursts','Outbursts inconsistent with developmental level','Outbursts ≥3×/week','Persistent irritability/anger between outbursts','Outbursts across multiple settings'],
 '12 months or longer; onset before age 10; diagnosis between 6–18',
 'Significant impairment across home, school, peers',
 '2–5% of children',
 'High risk of converting to unipolar depression/anxiety in adulthood',
 'Parent training, CBT, family therapy, treat comorbid ADHD, judicious medication (SSRIs, stimulants)',
 ARRAY['Bipolar disorder','ODD','IED','Autism','ADHD'],
 ARRAY['ADHD','ODD','Anxiety','Depression'],
 ARRAY['Family conflict','Trauma','Temperamental difficulty'],
 'Diagnosis ages 6–18 only','More common in males','—'),

-- ============ CHAPTER 5: ANXIETY ============
((SELECT id FROM dsm_chapters WHERE slug='anxiety'), 'separation-anxiety-disorder', 'Separation Anxiety Disorder', 'F93.0', '6B05',
 'Developmentally inappropriate and excessive fear/anxiety concerning separation from attachment figures.',
 ARRAY['Excessive distress about separation','Worry about losing attachment figures','Worry about untoward events causing separation','Reluctance to leave home or be alone','Refusal to sleep without being near attachment figure','Nightmares of separation','Physical complaints during separation'],
 '≥4 weeks in children/adolescents; ≥6 months in adults',
 'Impairs school/work attendance and relationships',
 '~4% in children; ~1–2% in adults',
 'Often waxes and wanes; may persist into adulthood',
 'CBT with exposure, parent involvement, school collaboration, SSRIs if severe',
 ARRAY['GAD','Social anxiety','Panic disorder','Agoraphobia','PTSD'],
 ARRAY['GAD','Specific phobias','Depression'],
 ARRAY['Parental overprotection','Loss/trauma','Genetic predisposition'],
 'Most common anxiety disorder in children under 12','More common in females','Cultural variation in independence expectations'),

((SELECT id FROM dsm_chapters WHERE slug='anxiety'), 'selective-mutism', 'Selective Mutism', 'F94.0', '6B06',
 'Consistent failure to speak in specific social situations where there is expectation for speaking, despite speaking in other situations.',
 ARRAY['Speaks comfortably at home but not at school','Uses gestures or whispers','Reliable silence in select contexts','Not due to language unfamiliarity'],
 'At least 1 month (not limited to first month of school)',
 'Interferes with educational/social achievement',
 '0.03–1% prevalence',
 'Often improves with intervention; can persist',
 'CBT (stimulus fading, shaping), school-based supports, SSRIs in resistant cases',
 ARRAY['Social anxiety disorder','Communication disorders','ASD','PTSD'],
 ARRAY['Social anxiety','Separation anxiety','Language disorder'],
 ARRAY['Behavioral inhibition','Bilingual transition','Family anxiety'],
 'Onset typically before age 5','Slight female predominance','Must be distinguished from second-language acquisition'),

((SELECT id FROM dsm_chapters WHERE slug='anxiety'), 'agoraphobia', 'Agoraphobia', 'F40.00', '6B02',
 'Marked fear/anxiety about two or more of: public transportation, open spaces, enclosed spaces, crowds, being outside the home alone.',
 ARRAY['Avoidance of feared situations','Need for companion','Endurance with intense fear','Fear of inability to escape','Panic-like symptoms in situations'],
 '6 months or more',
 'Often severe; can lead to housebound state',
 '~1.7% annually',
 'Chronic if untreated; responsive to therapy',
 'CBT with exposure, SSRIs/SNRIs, gradual desensitization',
 ARRAY['Specific phobia situational','Panic disorder','Social anxiety','PTSD','Major depression'],
 ARRAY['Panic disorder','Depression','Substance use'],
 ARRAY['Behavioral inhibition','Negative/stressful events','Family history'],
 'Bimodal peaks (childhood-adolescence and mid-30s)','2× more common in females','—'),

-- ============ CHAPTER 6: OCD AND RELATED ============
((SELECT id FROM dsm_chapters WHERE slug='ocd'), 'hoarding-disorder', 'Hoarding Disorder', 'F42.3', '6B24',
 'Persistent difficulty discarding possessions regardless of value, resulting in accumulation that congests living areas.',
 ARRAY['Difficulty discarding possessions','Strong urges to save','Distress at the thought of discarding','Cluttered living spaces','Avoidance of decisions about possessions','Indecisiveness','Perfectionism'],
 'Chronic; gradual onset',
 'Living areas unusable; safety, hygiene, and relational problems',
 '2–6% lifetime',
 'Chronic and worsening across decades',
 'CBT for hoarding, motivational interviewing, skills training (sorting, decision-making), SSRIs sometimes',
 ARRAY['OCD','Major depression','Autism','Dementia','Brain injury'],
 ARRAY['Depression','Anxiety','ADHD'],
 ARRAY['Family history','Stressful life events','Indecisiveness traits'],
 'Symptoms often begin in adolescence; severity increases with age','Equally common; severity higher in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='ocd'), 'trichotillomania', 'Trichotillomania (Hair-Pulling Disorder)', 'F63.3', '6B25.0',
 'Recurrent pulling out of one''s hair resulting in hair loss, despite repeated attempts to decrease or stop the behavior.',
 ARRAY['Hair pulling from scalp/eyebrows/lashes/body','Visible hair loss','Tension before pulling','Relief or pleasure during','Attempts to resist','Hiding behavior'],
 'Recurrent; not time-limited',
 'Functional, social and cosmetic distress',
 '1–2% lifetime',
 'Chronic, often with waxing/waning course',
 'Habit reversal therapy, ACT, family support, SSRIs with limited evidence',
 ARRAY['OCD','Excoriation','Body dysmorphic disorder','Dermatologic conditions'],
 ARRAY['Excoriation','Depression','Anxiety','OCD'],
 ARRAY['Female sex','Family history','Stressful life events'],
 'Onset typically peripubertal','More common in females (clinical samples)','Stigma may delay help-seeking'),

((SELECT id FROM dsm_chapters WHERE slug='ocd'), 'excoriation-disorder', 'Excoriation (Skin-Picking) Disorder', 'L98.1', '6B25.1',
 'Recurrent skin picking resulting in skin lesions, with repeated attempts to decrease or stop the behavior.',
 ARRAY['Picking at healthy or perceived imperfect skin','Lesions and scarring','Tension before picking','Relief during','Hiding skin areas','Time-consuming rituals'],
 'Recurrent',
 'Tissue damage, infections, social avoidance',
 '1.4–5.4% lifetime',
 'Chronic with fluctuating severity',
 'Habit reversal training, ACT, dermatology coordination, SSRIs sometimes',
 ARRAY['Trichotillomania','OCD','BDD','Dermatologic diseases'],
 ARRAY['Trichotillomania','Anxiety','Depression'],
 ARRAY['Female sex','Family history of OCRD','Adolescent onset triggers'],
 'Onset often adolescence','3:1 female predominance','—'),

-- ============ CHAPTER 7: TRAUMA ============
((SELECT id FROM dsm_chapters WHERE slug='trauma'), 'reactive-attachment-disorder', 'Reactive Attachment Disorder', 'F94.1', '6B44',
 'Pattern of inhibited, emotionally withdrawn behavior toward adult caregivers in children with histories of insufficient care.',
 ARRAY['Rarely seeks comfort when distressed','Rarely responds to comfort','Minimal social/emotional responsiveness','Limited positive affect','Unexplained irritability, sadness, fearfulness','History of inadequate caregiving'],
 'Symptoms before age 5; diagnosis after developmental age of 9 months',
 'Profound difficulties forming attachments and regulating emotion',
 '<1% even in high-risk groups',
 'Improvement with stable caregiving; without it, persistent',
 'Stable nurturing caregiving, dyadic therapies, foster/adoption support',
 ARRAY['ASD','Intellectual disability','Depression in children','Disinhibited social engagement disorder'],
 ARRAY['Developmental delays','Cognitive deficits'],
 ARRAY['Institutional care','Neglect','Multiple caregiver changes'],
 'Diagnosis under 5 only','Equal across sexes','Cultural caregiving norms must be considered'),

((SELECT id FROM dsm_chapters WHERE slug='trauma'), 'disinhibited-social-engagement-disorder', 'Disinhibited Social Engagement Disorder', 'F94.2', '6B45',
 'Pattern of behavior in which a child actively approaches and interacts with unfamiliar adults without normal reticence.',
 ARRAY['Reduced/absent reticence with strangers','Overly familiar verbal/physical behavior','Willingness to go off with unfamiliar adults','Decreased checking back with caregiver','History of insufficient care'],
 'Onset before age 5; diagnosable at developmental age ≥9 months',
 'Safety concerns; impaired relationships',
 'Rare; up to 20% of severely neglected children',
 'May persist even after stable caregiving',
 'Stable caregiving, attachment-based interventions, safety planning, school supports',
 ARRAY['ADHD','Williams syndrome','Personality traits'],
 ARRAY['ADHD','Cognitive delays'],
 ARRAY['Institutional rearing','Severe neglect','Caregiver changes'],
 'Diagnosis under 5','Equal across sexes','Cultural display rules must be considered'),

((SELECT id FROM dsm_chapters WHERE slug='trauma'), 'prolonged-grief-disorder', 'Prolonged Grief Disorder', 'F43.81', '6B42',
 'Persistent and pervasive grief response characterized by intense yearning and preoccupation with the deceased, far beyond cultural and contextual norms.',
 ARRAY['Intense yearning for the deceased','Preoccupation with the deceased','Identity disruption','Marked sense of disbelief','Avoidance of reminders','Intense emotional pain','Loneliness','Numbness','Meaninglessness'],
 'At least 12 months post-loss in adults (6 months in children/adolescents)',
 'Significant impairment in functioning',
 '~10% of bereaved adults',
 'Chronic if untreated; responsive to targeted therapy',
 'Complicated grief treatment, CBT, peer support, antidepressants if comorbid depression',
 ARRAY['Normal grief','Major depression','PTSD','Adjustment disorder'],
 ARRAY['Depression','PTSD','Substance use'],
 ARRAY['Sudden/violent loss','Loss of child/partner','Low social support','Insecure attachment'],
 'Distinct criteria for children','More common in females','Mourning rituals vary widely'),

-- ============ CHAPTER 8: DISSOCIATIVE ============
((SELECT id FROM dsm_chapters WHERE slug='dissociative'), 'dissociative-amnesia', 'Dissociative Amnesia', 'F44.0', '6B61',
 'Inability to recall important autobiographical information, usually of traumatic or stressful nature, inconsistent with ordinary forgetting.',
 ARRAY['Localized amnesia (specific event)','Selective amnesia','Generalized amnesia (rare)','Dissociative fugue (with travel)','Distress or impairment'],
 'Episodes vary; may resolve suddenly',
 'Disruption to identity and daily life',
 '~1.8% past year',
 'May resolve spontaneously; chronic in subsets',
 'Phase-oriented trauma therapy, supportive psychotherapy, safety planning',
 ARRAY['Neurocognitive disorders','TBI','Substance-induced amnesia','PTSD','DID'],
 ARRAY['PTSD','Depression','Anxiety','DID'],
 ARRAY['Severe trauma','Repeated abuse','Combat exposure'],
 'Can occur at any age','More common in females','Cultural variants of trance/possession'),

((SELECT id FROM dsm_chapters WHERE slug='dissociative'), 'depersonalization-derealization-disorder', 'Depersonalization/Derealization Disorder', 'F48.1', '6B66',
 'Persistent or recurrent experiences of feeling detached from oneself (depersonalization) or surroundings (derealization), with intact reality testing.',
 ARRAY['Feeling unreal/detached from body','Emotional numbing','Distorted sense of time','Feeling like an outside observer','Surroundings appear dreamlike','Visual distortions of environment'],
 'Recurrent or persistent',
 'Marked distress and impairment',
 '~2% lifetime',
 'Often chronic with fluctuating intensity',
 'Psychoeducation, grounding techniques, CBT, treat comorbid anxiety/depression',
 ARRAY['Panic disorder','Substance/medication effects','Psychotic disorders','PTSD','Seizure disorders'],
 ARRAY['Anxiety','Depression','PTSD'],
 ARRAY['Childhood emotional abuse','Trauma','Severe stress'],
 'Onset typically mid-teens to twenties','Equal across sexes','—'),

-- ============ CHAPTER 9: SOMATIC SYMPTOM AND RELATED ============
((SELECT id FROM dsm_chapters WHERE slug='somatic'), 'somatic-symptom-disorder', 'Somatic Symptom Disorder', 'F45.1', '6C20',
 'One or more distressing somatic symptoms with excessive thoughts, feelings, or behaviors related to them.',
 ARRAY['Disproportionate health-related thoughts','High health anxiety','Excessive time/energy devoted to symptoms','Persistent symptoms (typically >6 months)','Frequent medical visits'],
 'At least 6 months',
 'Substantial functional impact and healthcare utilization',
 '5–7% of general adult population',
 'Often chronic with relapses',
 'CBT, regular primary care visits with one provider, mindfulness, treat depression/anxiety',
 ARRAY['Illness anxiety','Depression','Anxiety','General medical conditions','Factitious disorder'],
 ARRAY['Depression','Anxiety','Personality disorders'],
 ARRAY['Female sex','Adverse childhood experiences','Concurrent medical illness'],
 'Onset typically before 30','More common in females','Symptom expression varies culturally'),

((SELECT id FROM dsm_chapters WHERE slug='somatic'), 'illness-anxiety-disorder', 'Illness Anxiety Disorder', 'F45.21', '6B23',
 'Preoccupation with having or acquiring a serious illness; somatic symptoms are not present or are mild.',
 ARRAY['High anxiety about health','Excessive health-related behaviors (checking) or maladaptive avoidance','Preoccupation despite reassurance','Easily alarmed about personal health'],
 'At least 6 months',
 'Significant distress and impairment',
 '1.3–10% lifetime',
 'Often chronic with relapses',
 'CBT, exposure and response prevention, mindfulness, limit reassurance-seeking, SSRIs',
 ARRAY['Somatic symptom disorder','OCD','GAD','Major depression','Delusional disorder somatic'],
 ARRAY['Anxiety','Depression','Personality disorders'],
 ARRAY['Major life stress','Childhood illness','Family illness history'],
 'Typically begins early/middle adulthood','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='somatic'), 'conversion-disorder', 'Functional Neurological Symptom Disorder (Conversion)', 'F44.x', '6B60',
 'One or more symptoms of altered voluntary motor or sensory function incompatible with recognized neurological conditions.',
 ARRAY['Weakness/paralysis','Abnormal movements (tremor, dystonia)','Swallowing or speech symptoms','Seizure-like episodes (PNES)','Sensory loss','Visual/hearing disturbance','Mixed symptoms'],
 'Symptoms acute or persistent',
 'Major functional impact and healthcare utilization',
 '~2–5 per 100,000 yearly incidence',
 'Variable; acute onset often improves; chronic forms persist',
 'Multidisciplinary care, physiotherapy, CBT, education about diagnosis, treat psychiatric comorbidity',
 ARRAY['Neurologic disease (MS, epilepsy)','Factitious disorder','Malingering','Substance effects'],
 ARRAY['Depression','Anxiety','PTSD','Personality disorders'],
 ARRAY['Trauma','Major stressors','Neurologic disease comorbidity'],
 'Can occur at any age','2–3× more common in females','Cultural idioms of distress influence presentation'),

((SELECT id FROM dsm_chapters WHERE slug='somatic'), 'factitious-disorder', 'Factitious Disorder', 'F68.10', '6D50',
 'Falsification of physical or psychological signs/symptoms, or induction of injury/disease, in self or another, without obvious external rewards.',
 ARRAY['Fabricating symptoms','Inducing injury or illness','Exaggerating real conditions','Seeking medical procedures','Deceptive behavior toward providers'],
 'Episodic or persistent',
 'Serious medical harm; relationship/legal consequences',
 'Unknown; ~1% of hospital patients',
 'Variable; chronic in many cases',
 'Non-confrontational engagement, mental health referral, coordination across providers, safety planning',
 ARRAY['Somatic symptom disorder','Malingering','Conversion disorder','Borderline personality'],
 ARRAY['Personality disorders','Depression','Substance use'],
 ARRAY['Healthcare exposure','Childhood illness','Personality factors'],
 'Onset usually early adulthood','More common in females','—'),

-- ============ CHAPTER 10: EATING ============
((SELECT id FROM dsm_chapters WHERE slug='eating'), 'pica', 'Pica', 'F50.8', '6B84',
 'Persistent eating of nonnutritive, nonfood substances inappropriate to developmental level.',
 ARRAY['Eating dirt, clay, paper, hair, paint chips','Persistent for ≥1 month','Not culturally sanctioned','Not part of normal developmental exploration'],
 'At least 1 month',
 'Medical risks (poisoning, obstruction, infection)',
 'Variable; higher in ID and pregnancy',
 'Often remits in childhood; persistent in some ID cases',
 'Behavioral interventions, address nutritional deficiencies, environmental modifications, monitor complications',
 ARRAY['Normal exploration','OCD','Schizophrenia','Autism','Cultural practices'],
 ARRAY['ID','ASD','Iron-deficiency anemia'],
 ARRAY['ID','Neglect','Pregnancy','Nutritional deficiency'],
 'Minimum mental age of 2 for diagnosis','Slightly more in females during pregnancy','Cultural geophagy excluded'),

((SELECT id FROM dsm_chapters WHERE slug='eating'), 'rumination-disorder', 'Rumination Disorder', 'F98.21', '6B85',
 'Repeated regurgitation of food, which may be re-chewed, re-swallowed, or spit out.',
 ARRAY['Effortless regurgitation','Re-chewing/re-swallowing food','Onset typically postprandial','Weight loss/failure to thrive','Halitosis'],
 'At least 1 month',
 'Nutritional and dental complications, social distress',
 'Unknown; underdiagnosed',
 'Often resolves spontaneously; can persist',
 'Diaphragmatic breathing, behavioral therapy, address stressors, treat reflux',
 ARRAY['GERD','Achalasia','Bulimia nervosa','Anorexia','Gastroparesis'],
 ARRAY['Anxiety','Depression','ID'],
 ARRAY['Stress','ID','Neglect'],
 'Common in infancy and ID populations','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='eating'), 'arfid', 'Avoidant/Restrictive Food Intake Disorder (ARFID)', 'F50.82', '6B83',
 'Eating or feeding disturbance leading to persistent failure to meet appropriate nutritional/energy needs, without body image disturbance.',
 ARRAY['Lack of interest in food','Avoidance based on sensory characteristics','Concern about aversive consequences (choking)','Significant weight loss/poor growth','Nutritional deficiency','Dependence on supplements','Marked psychosocial interference'],
 'Persistent; no time minimum',
 'Medical, nutritional, and psychosocial impairment',
 '~0.3–3%; higher in pediatric clinics',
 'Variable; can persist into adulthood',
 'Multidisciplinary feeding team, CBT-AR, family-based therapy, address nutritional gaps',
 ARRAY['Anorexia nervosa','Specific phobia','Autism','GI disorders','OCD'],
 ARRAY['ASD','Anxiety','OCD'],
 ARRAY['Sensory sensitivities','Choking event','GI illness'],
 'Often begins in childhood','Equal across sexes (varies by subtype)','—'),

-- ============ CHAPTER 11: ELIMINATION ============
((SELECT id FROM dsm_chapters WHERE slug='elimination'), 'enuresis', 'Enuresis', 'F98.0', '6C00',
 'Repeated voiding of urine into clothes or bed, whether involuntary or intentional.',
 ARRAY['Bedwetting (nocturnal)','Daytime wetting (diurnal)','Mixed pattern','Distress or impairment'],
 'At least twice weekly for 3 months or with marked distress; chronological age ≥5',
 'Social, emotional and family distress',
 '5–10% at age 5; declines with age',
 'Most resolve by adolescence',
 'Bladder training, bedwetting alarm, desmopressin, address constipation, behavioral techniques',
 ARRAY['UTI','Diabetes','Spina bifida','Side effects'],
 ARRAY['ADHD','Constipation','Sleep disorders'],
 ARRAY['Family history','Delayed bladder maturation','Stress'],
 'Higher prevalence in males','Slightly more common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='elimination'), 'encopresis', 'Encopresis', 'F98.1', '6C01',
 'Repeated passage of feces into inappropriate places, whether involuntary or intentional.',
 ARRAY['Soiling clothing','Constipation with overflow','Avoidance of toileting','Hiding soiled clothes','Skin irritation'],
 'At least once monthly for 3 months; chronological age ≥4',
 'Significant social and emotional distress',
 '~1% of 5-year-olds',
 'Usually resolves by adolescence with treatment',
 'Disimpaction, maintenance laxatives, behavioral toileting program, family support',
 ARRAY['Hirschsprung disease','Anatomic anomalies','Medication side effects','Hypothyroidism'],
 ARRAY['ADHD','Anxiety','ODD'],
 ARRAY['Painful defecation','Toileting refusal','Stressful events'],
 'More common in males','3–6× more common in males','—'),

-- ============ CHAPTER 12: SLEEP-WAKE ============
((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'hypersomnolence-disorder', 'Hypersomnolence Disorder', 'G47.10', '7A20',
 'Excessive sleepiness despite a main sleep period lasting at least 7 hours, with recurrent lapses or prolonged unrefreshing sleep.',
 ARRAY['Recurrent daytime sleep episodes','Prolonged non-restorative sleep >9h','Difficulty being fully awake after abrupt awakening (sleep inertia)','Cognitive dysfunction','Memory problems'],
 'At least 3×/week for 3 months',
 'Impaired work, school, and social functioning',
 '~1% adults',
 'Chronic and persistent',
 'Sleep hygiene, stimulants (modafinil), treat comorbid conditions',
 ARRAY['Narcolepsy','OSA','Insufficient sleep','Depression','Substance use'],
 ARRAY['Depression','OSA','Substance use'],
 ARRAY['Family history','Viral infection','Head trauma'],
 'Onset typically late teens/early 20s','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'narcolepsy', 'Narcolepsy', 'G47.4', '7A20.0',
 'Recurrent periods of irrepressible need to sleep, lapsing into sleep, or napping; with cataplexy, hypocretin deficiency, or REM-sleep abnormalities.',
 ARRAY['Sleep attacks','Cataplexy (sudden muscle weakness)','Sleep paralysis','Hypnagogic/hypnopompic hallucinations','Disrupted nocturnal sleep'],
 'At least 3×/week over 3 months',
 'Major impact on safety, school, work, driving',
 '~0.02–0.18%',
 'Chronic; lifelong',
 'Scheduled naps, modafinil/armodafinil, sodium oxybate, pitolisant, antidepressants for cataplexy',
 ARRAY['OSA','Hypersomnolence','Seizures','Syncope'],
 ARRAY['Depression','OSA','Obesity'],
 ARRAY['HLA-DQB1*06:02','H1N1 vaccine (Pandemrix)','Family history'],
 'Onset typically adolescence','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'osa-hypopnea', 'Obstructive Sleep Apnea Hypopnea', 'G47.33', '7A41',
 'Repeated episodes of upper airway obstruction during sleep, evidenced by polysomnography.',
 ARRAY['Loud snoring','Witnessed apneas','Gasping during sleep','Excessive daytime sleepiness','Morning headaches','Nonrestorative sleep'],
 'Ongoing pattern',
 'Cardiovascular, metabolic, and cognitive consequences',
 '~9–38% of adults (varies by criteria)',
 'Chronic and progressive without treatment',
 'CPAP, weight loss, oral appliances, positional therapy, surgery in select cases',
 ARRAY['Central sleep apnea','Obesity hypoventilation','Insomnia','Hypothyroidism'],
 ARRAY['HTN','T2DM','Heart failure','Depression'],
 ARRAY['Obesity','Male sex','Older age','Craniofacial features','Family history'],
 'Increases with age','2–3× more common in males (premenopausal)','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'circadian-rhythm-sleep-disorder', 'Circadian Rhythm Sleep–Wake Disorders', 'G47.2', '7A60',
 'Persistent or recurrent pattern of sleep disruption due to alteration of the circadian system or misalignment between endogenous rhythm and required sleep-wake schedule.',
 ARRAY['Delayed sleep phase','Advanced sleep phase','Irregular sleep–wake','Non-24-hour pattern','Shift work pattern','Jet lag pattern'],
 'At least 3 months',
 'Impaired daytime functioning',
 'Variable by subtype; ~7–16% of adolescents have delayed phase',
 'Often chronic; modifiable',
 'Timed light exposure, melatonin, scheduled sleep, chronotherapy, address shift work',
 ARRAY['Insomnia','Mood disorders','Poor sleep hygiene'],
 ARRAY['Depression','Anxiety','Substance use'],
 ARRAY['Adolescence','Shift work','Travel','Blindness'],
 'Delayed type peaks in adolescence','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'nrem-sleep-arousal-disorder', 'NREM Sleep Arousal Disorders (Sleepwalking & Sleep Terrors)', 'F51.3/F51.4', '7B00',
 'Recurrent episodes of incomplete awakening from sleep, with sleepwalking or sleep terror manifestations and amnesia for the episodes.',
 ARRAY['Sleepwalking with complex behaviors','Sudden arousal with panicky scream','Intense fear and autonomic arousal','Unresponsiveness during episode','Amnesia for the episode'],
 'Recurrent',
 'Risk of injury; family disruption',
 'Sleepwalking ~7% lifetime; terrors ~1–6% in children',
 'Often resolves by adolescence',
 'Safety measures, scheduled awakening, address sleep deprivation, treat triggers, low-dose benzodiazepines if severe',
 ARRAY['Nightmare disorder','REM sleep behavior disorder','Seizures','Dissociative episodes'],
 ARRAY['OSA','Restless legs','Anxiety'],
 ARRAY['Family history','Sleep deprivation','Fever','Stress','Medications'],
 'More common in children','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'nightmare-disorder', 'Nightmare Disorder', 'F51.5', '7B01',
 'Repeated occurrences of extended, extremely dysphoric, and well-remembered dreams.',
 ARRAY['Vivid threatening dreams','Rapid orientation upon awakening','Distress on awakening','Avoidance of sleep','Daytime fatigue'],
 'At least 1 month',
 'Sleep disturbance and daytime distress',
 'Frequent nightmares in 2–8% adults',
 'Often chronic if untreated',
 'Imagery rehearsal therapy, CBT-I, prazosin for trauma-related, address triggers',
 ARRAY['PTSD','Sleep terrors','Substance/medication','REM behavior disorder'],
 ARRAY['PTSD','Depression','Anxiety'],
 ARRAY['Trauma','Substances','Stress','Family history'],
 'Common in childhood; can persist','More common in females','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'rem-sleep-behavior-disorder', 'REM Sleep Behavior Disorder', 'G47.52', '7B02',
 'Repeated episodes of arousal during REM sleep associated with vocalization and/or complex motor behaviors.',
 ARRAY['Dream enactment','Vocalizations during sleep','Violent movements','Falling out of bed','Injury to self or bed partner'],
 'Recurrent; documented by polysomnography',
 'Injury risk; predictor of neurodegenerative disease',
 '~0.4–0.5% adults',
 'Chronic; high conversion to synucleinopathies',
 'Safety measures, melatonin, clonazepam, screen for Parkinsonian disorders',
 ARRAY['NREM arousal disorder','Nocturnal seizures','OSA-related arousals'],
 ARRAY['Parkinson disease','Lewy body dementia','MSA'],
 ARRAY['Male sex','Older age','SSRIs/SNRIs','Synucleinopathy risk'],
 'Most cases >50 years','Strong male predominance','—'),

((SELECT id FROM dsm_chapters WHERE slug='sleep-wake'), 'restless-legs-syndrome', 'Restless Legs Syndrome', 'G25.81', '7A80',
 'Urge to move the legs, usually accompanied by uncomfortable sensations, worsened by rest and relieved by movement, predominantly in evening or night.',
 ARRAY['Urge to move legs','Crawling, tingling, aching sensations','Worse with rest','Relief with movement','Worse in evening/night'],
 'At least 3×/week for 3 months',
 'Insomnia, daytime fatigue, mood symptoms',
 '2–7% adults',
 'Chronic; often progressive',
 'Iron repletion if low ferritin, alpha-2-delta ligands (gabapentin), dopamine agonists (caution for augmentation)',
 ARRAY['Akathisia','Peripheral neuropathy','Leg cramps','Positional discomfort'],
 ARRAY['Iron deficiency','Insomnia','Depression'],
 ARRAY['Iron deficiency','Pregnancy','ESRD','Family history'],
 'Increases with age','More common in females','—'),

-- ============ CHAPTER 13: SEXUAL DYSFUNCTIONS ============
((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'delayed-ejaculation', 'Delayed Ejaculation', 'F52.32', '6D72',
 'Marked delay in, or marked infrequency or absence of ejaculation despite adequate sexual stimulation.',
 ARRAY['Delay or absence of ejaculation','Distress','Avoidance of intimacy'],
 'At least 6 months in ≥75% of sexual activity',
 'Relationship distress; reproductive concerns',
 '<1% sustained complaints',
 'Variable; lifelong or acquired',
 'Sex therapy, address medications (e.g., SSRIs), couples therapy',
 ARRAY['Medication effects','Hypogonadism','Neurologic disease','Relationship issues'],
 ARRAY['Depression','Anxiety'],
 ARRAY['Aging','SSRIs','Diabetes','Neurologic conditions'],
 'Older men more affected','Male diagnosis','—'),

((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'erectile-disorder', 'Erectile Disorder', 'F52.21', '6D70',
 'Recurrent failure to attain or maintain erection sufficient for sexual activity.',
 ARRAY['Difficulty obtaining erection','Difficulty maintaining erection','Decreased erectile rigidity','Performance anxiety'],
 'At least 6 months in ≥75% of activity',
 'Distress and relational impact',
 '~13–21% adult men; rises with age',
 'May be lifelong or acquired; often progressive without treatment',
 'PDE5 inhibitors, treat vascular risk, psychotherapy, couples therapy, vacuum devices',
 ARRAY['Vascular disease','Medication side effects','Hypogonadism','Performance anxiety'],
 ARRAY['Depression','Diabetes','CV disease'],
 ARRAY['Age','Diabetes','Smoking','Obesity','SSRI use'],
 'Increases with age','Male diagnosis','—'),

((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'female-orgasmic-disorder', 'Female Orgasmic Disorder', 'F52.31', '6D71',
 'Marked delay in, infrequency of, or absence of orgasm, or markedly reduced intensity of orgasmic sensations.',
 ARRAY['Difficulty reaching orgasm','Reduced orgasmic intensity','Distress about orgasmic experience'],
 'At least 6 months in ≥75% of activity',
 'Sexual and relationship distress',
 '10–42% lifetime complaints; many without distress',
 'Lifelong or acquired',
 'Sex therapy, mindfulness, directed masturbation, couples therapy',
 ARRAY['Medication effects','Hormonal issues','Relationship issues'],
 ARRAY['Depression','Anxiety'],
 ARRAY['SSRI use','Trauma','Relationship issues','Aging'],
 '—','Female diagnosis','Cultural norms vary widely'),

((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'female-sexual-interest-arousal-disorder', 'Female Sexual Interest/Arousal Disorder', 'F52.22', '6D71.0',
 'Lack of, or significantly reduced, sexual interest/arousal across at least 3 of: interest, sexual thoughts, initiation, excitement, response.',
 ARRAY['Low sexual interest','Reduced erotic thoughts','Reduced initiation','Reduced excitement','Reduced genital sensations'],
 'At least 6 months',
 'Significant distress',
 '20–30% complaints; ~10% with distress',
 'Often persistent without treatment',
 'Sex therapy, mindfulness, address relationship factors, treat hormonal issues',
 ARRAY['Major depression','Medication effects','Relationship issues','Medical disease'],
 ARRAY['Depression','Anxiety'],
 ARRAY['Relationship stress','Hormonal changes','Medications'],
 'Higher in postmenopause','Female diagnosis','—'),

((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'genito-pelvic-pain-penetration-disorder', 'Genito-Pelvic Pain/Penetration Disorder', 'F52.6', '6D75',
 'Persistent difficulties with vaginal penetration, pain during intercourse, fear of pain, or tensing of pelvic floor muscles.',
 ARRAY['Difficulty with penetration','Vulvovaginal/pelvic pain during intercourse','Fear/anxiety about pain','Pelvic floor tensing','Avoidance of intercourse'],
 'At least 6 months',
 'Sexual avoidance and distress',
 '~15% of women in some samples',
 'Often persistent without treatment',
 'Pelvic floor PT, CBT, sex therapy, vaginal dilators, treat vulvar disorders',
 ARRAY['Vulvodynia','Endometriosis','Vaginal atrophy','Vaginismus','Infection'],
 ARRAY['Anxiety','Depression'],
 ARRAY['History of pelvic pain','Trauma','Childbirth','Hormonal changes'],
 '—','Female diagnosis','—'),

((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'male-hypoactive-sexual-desire-disorder', 'Male Hypoactive Sexual Desire Disorder', 'F52.0', '6D71.2',
 'Persistent or recurrent deficiency or absence of sexual/erotic thoughts and desire.',
 ARRAY['Low libido','Reduced erotic thoughts','Reduced desire for sexual activity'],
 'At least 6 months',
 'Personal and relational distress',
 '~6% young men; ~41% older men',
 'May be lifelong or acquired',
 'Address hypogonadism, medication review, sex therapy, couples therapy',
 ARRAY['Major depression','Hypogonadism','Medication effects'],
 ARRAY['Depression','Substance use'],
 ARRAY['Aging','Low testosterone','SSRIs','Stress'],
 'Increases with age','Male diagnosis','—'),

((SELECT id FROM dsm_chapters WHERE slug='sexual'), 'premature-early-ejaculation', 'Premature (Early) Ejaculation', 'F52.4', '6D73',
 'Persistent pattern of ejaculation within approximately 1 minute of vaginal penetration and before the person wishes it.',
 ARRAY['Rapid ejaculation','Inability to delay','Distress and frustration','Avoidance of intimacy'],
 'At least 6 months in ≥75% of activity',
 'Relationship and personal distress',
 '20–30% of men by self-report',
 'Lifelong or acquired',
 'Behavioral techniques (stop-start, squeeze), SSRIs, topical anesthetics, couples therapy',
 ARRAY['Performance anxiety','Substance withdrawal','Prostatitis'],
 ARRAY['Anxiety','Depression'],
 ARRAY['Anxiety','Inexperience','Thyroid dysfunction'],
 '—','Male diagnosis','—'),

-- ============ CHAPTER 14: GENDER DYSPHORIA ============
((SELECT id FROM dsm_chapters WHERE slug='gender-dysphoria'), 'gender-dysphoria-children', 'Gender Dysphoria in Children', 'F64.2', '6B00',
 'Marked incongruence between experienced/expressed gender and assigned gender, with strong desire to be of another gender, in children.',
 ARRAY['Strong desire to be of another gender','Preference for cross-gender roles','Strong preference for clothing typical of another gender','Strong preference for cross-gender playmates','Rejection of toys/games typically associated with assigned gender','Dislike of one''s sexual anatomy','Strong desire for primary/secondary sex characteristics of experienced gender'],
 'At least 6 months',
 'Clinically significant distress or impairment',
 '~0.7% of children',
 'Variable; many youth experience desistance; some persist',
 'Gender-affirming psychosocial support, family education, school accommodations, watchful waiting',
 ARRAY['Nonconformity without distress','OCD','Body dysmorphic disorder','Psychotic disorders'],
 ARRAY['Anxiety','Depression','Autism'],
 ARRAY['Family rejection','Bullying'],
 'Specific to childhood','Across all assigned genders','Cultural norms shape expression and access'),

((SELECT id FROM dsm_chapters WHERE slug='gender-dysphoria'), 'gender-dysphoria-adolescents-adults', 'Gender Dysphoria in Adolescents and Adults', 'F64.0', '6B01',
 'Marked incongruence between experienced/expressed gender and assigned gender in adolescents and adults, with distress or impairment.',
 ARRAY['Incongruence between experienced gender and primary/secondary sex characteristics','Desire to be rid of primary/secondary sex characteristics','Desire for primary/secondary characteristics of experienced gender','Desire to be treated as another gender','Strong conviction one has the typical feelings of another gender'],
 'At least 6 months',
 'Significant distress, social, occupational, or family impairment',
 '~0.005–0.014% (clinical estimates; community far higher)',
 'Often persistent into adulthood',
 'Gender-affirming care (psychotherapy, hormones, surgery as indicated), peer support, family work',
 ARRAY['Transvestic disorder','Body dysmorphic disorder','Schizophrenia spectrum'],
 ARRAY['Anxiety','Depression','Suicidality','PTSD'],
 ARRAY['Discrimination','Family rejection','Violence'],
 'Onset can be early or late','Across all assigned genders','Access to affirming care varies globally'),

-- ============ CHAPTER 15: IMPULSE-CONTROL ============
((SELECT id FROM dsm_chapters WHERE slug='impulse-control'), 'oppositional-defiant-disorder', 'Oppositional Defiant Disorder', 'F91.3', '6C90',
 'Pattern of angry/irritable mood, argumentative/defiant behavior, or vindictiveness lasting at least 6 months.',
 ARRAY['Loses temper','Easily annoyed','Angry and resentful','Argues with authority','Defies rules/requests','Deliberately annoys others','Blames others for mistakes','Spiteful or vindictive'],
 'At least 6 months',
 'Impairs family, school, and peer relationships',
 '~3.3% of children',
 'Often precursor to conduct disorder or mood disorders',
 'Parent management training, family therapy, CBT, treat ADHD/comorbidities',
 ARRAY['Conduct disorder','ADHD','DMDD','Depression','Anxiety'],
 ARRAY['ADHD','Anxiety','Depression','Learning disorders'],
 ARRAY['Harsh parenting','Maltreatment','Difficult temperament'],
 'Symptoms usually before age 8','More common in males during childhood','—'),

((SELECT id FROM dsm_chapters WHERE slug='impulse-control'), 'intermittent-explosive-disorder', 'Intermittent Explosive Disorder', 'F63.81', '6C73',
 'Recurrent behavioral outbursts representing failure to control aggressive impulses, grossly out of proportion to provocation.',
 ARRAY['Verbal aggression (twice weekly for 3 months)','Behavioral aggression with damage/injury (3 episodes in 12 months)','Impulsive/anger-based outbursts','Marked distress or impairment','Outbursts not premeditated'],
 'Outbursts pattern as above; minimum age 6',
 'Legal, occupational, and relational consequences',
 '~2.7% adults',
 'Onset typically childhood/adolescence; chronic',
 'CBT for anger, SSRIs, mood stabilizers in select cases, treat substance use',
 ARRAY['ASPD','Borderline PD','Bipolar disorder','Conduct disorder','TBI'],
 ARRAY['Depression','Anxiety','Substance use'],
 ARRAY['Childhood trauma','Family history','Frontal lobe dysfunction'],
 'Onset usually before age 20','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='impulse-control'), 'pyromania', 'Pyromania', 'F63.1', '6C71',
 'Deliberate and purposeful fire setting on more than one occasion, with tension/arousal before and pleasure/relief during or after.',
 ARRAY['Recurrent fire setting','Tension before act','Fascination with fire','Pleasure/relief during fires','Not for monetary gain or vengeance'],
 'Recurrent',
 'Legal and safety consequences',
 'Rare; <1%',
 'Chronic without treatment',
 'CBT, address comorbid substance use/mood, court-involved treatment',
 ARRAY['Conduct disorder','ASPD','Substance intoxication','Psychotic disorders','Cognitive impairment'],
 ARRAY['Substance use','Mood disorders','Personality disorders'],
 ARRAY['Childhood trauma','Family dysfunction'],
 'Often begins adolescence','Most cases male','—'),

((SELECT id FROM dsm_chapters WHERE slug='impulse-control'), 'kleptomania', 'Kleptomania', 'F63.2', '6C72',
 'Recurrent failure to resist impulses to steal objects not needed for personal use or monetary value.',
 ARRAY['Recurrent stealing','Tension before act','Pleasure/relief during','Items not needed','Not for vengeance or hallucinations'],
 'Recurrent',
 'Legal, social, and occupational problems',
 '~0.3–0.6% prevalence',
 'Chronic with waxing/waning course',
 'CBT, naltrexone, SSRIs, court-involved treatment',
 ARRAY['Conduct disorder','ASPD','Bipolar disorder mania','Psychotic disorders'],
 ARRAY['Mood disorders','Substance use','Eating disorders'],
 ARRAY['Family history','Childhood trauma'],
 'Onset typically adolescence','More common in females in clinical samples','—'),

-- ============ CHAPTER 16: SUBSTANCE-RELATED & ADDICTIVE ============
((SELECT id FROM dsm_chapters WHERE slug='substance'), 'cannabis-use-disorder', 'Cannabis Use Disorder', 'F12.2', '6C41',
 'Problematic pattern of cannabis use leading to clinically significant impairment or distress.',
 ARRAY['Larger amounts than intended','Unsuccessful efforts to cut down','Time spent obtaining/using','Cravings','Role failure','Continued use despite problems','Tolerance','Withdrawal (irritability, sleep difficulty)'],
 'Within a 12-month period',
 'Occupational, academic, and relationship impact',
 '~6.3% adults past-year',
 'Variable; chronic in many cases',
 'Motivational interviewing, CBT, contingency management, treat comorbid conditions',
 ARRAY['Other substance use','Mood disorders','Anxiety','Psychosis'],
 ARRAY['Mood disorders','Anxiety','Other SUDs'],
 ARRAY['Early initiation','Family history','Mental illness'],
 'Onset typically adolescence','More common in males','Legal status and norms vary widely'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'stimulant-use-disorder', 'Stimulant Use Disorder', 'F15.2', '6C46',
 'Problematic pattern of amphetamine-type, cocaine, or other stimulant use leading to clinically significant impairment or distress.',
 ARRAY['Compulsive use','Cravings','Tolerance','Withdrawal (dysphoria, fatigue, vivid dreams)','Role failures','Continued use despite cardiovascular or psychiatric harm','Binge–crash cycle'],
 'Within 12 months',
 'Cardiac, neurologic, psychiatric, and social consequences',
 '~0.8% past-year for cocaine; rising methamphetamine prevalence',
 'High relapse risk; chronic relapsing course',
 'Contingency management, CBT, community reinforcement, treat comorbid mood/anxiety',
 ARRAY['Bipolar disorder mania','ADHD','Psychotic disorders'],
 ARRAY['Depression','Anxiety','Other SUDs'],
 ARRAY['Family history','Trauma','Mental illness'],
 'Often emerges in early adulthood','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'tobacco-use-disorder', 'Tobacco Use Disorder', 'F17.2', '6C4A',
 'Problematic pattern of tobacco/nicotine use leading to clinically significant impairment or distress.',
 ARRAY['Larger amounts than intended','Failed quit attempts','Cravings','Continued use despite physical problems','Withdrawal (irritability, anxiety, sleep, appetite)','Tolerance'],
 'Within 12 months',
 'Major morbidity/mortality risk',
 '~20% adults globally',
 'Chronic relapsing; many achieve cessation',
 'NRT, varenicline, bupropion, behavioral support, motivational interviewing',
 ARRAY['Other substance use','Anxiety','Depression'],
 ARRAY['COPD','CV disease','Cancer','Depression'],
 ARRAY['Family history','Peer use','Mental illness'],
 'Onset usually adolescence','Approaching parity globally','Tobacco norms vary widely'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'sedative-hypnotic-use-disorder', 'Sedative, Hypnotic, or Anxiolytic Use Disorder', 'F13.2', '6C44',
 'Problematic pattern of sedative-hypnotic/anxiolytic use causing significant impairment or distress.',
 ARRAY['Use beyond prescribed amount','Cravings','Tolerance','Withdrawal (autonomic hyperactivity, tremor, seizures)','Role impairment','Doctor shopping','Continued use despite harm'],
 'Within 12 months',
 'Cognitive impairment, falls, overdose risk',
 '~0.3–1% past-year',
 'Chronic relapsing course; complicated by withdrawal danger',
 'Gradual taper, CBT, alternative anxiety/insomnia treatments, treat comorbidities',
 ARRAY['Alcohol use disorder','Opioid use disorder','Anxiety disorders'],
 ARRAY['Depression','Anxiety','Other SUDs'],
 ARRAY['Co-prescription','Chronic anxiety','Pain conditions'],
 'Higher with age','Slightly more in females','—'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'hallucinogen-use-disorder', 'Hallucinogen Use Disorder', 'F16.2', '6C43',
 'Problematic pattern of hallucinogen use leading to clinically significant impairment or distress.',
 ARRAY['Frequent use','Continued use despite problems','Cravings','Role failures','Tolerance (LSD specifically)','Risky use'],
 'Within 12 months',
 'Risk of perceptual disturbances, accidents, persisting perception disorder',
 '<1% past-year',
 'Variable; many use episodically',
 'Motivational interviewing, CBT, address triggers, treat comorbid psychiatric conditions',
 ARRAY['Other substance use','Psychotic disorders','Anxiety disorders'],
 ARRAY['Other SUDs','Anxiety','Depression'],
 ARRAY['Adolescence','Peer use','Mental illness'],
 'Mostly adolescents/young adults','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'inhalant-use-disorder', 'Inhalant Use Disorder', 'F18.2', '6C4B',
 'Problematic pattern of inhalant use (solvents, fuels, nitrites) causing significant impairment or distress.',
 ARRAY['Use of glue, paint, gasoline, butane, nitrites','Cravings','Tolerance','Continued use despite neurologic harm','Role failures','Persistent use despite legal problems'],
 'Within 12 months',
 'Severe neurologic damage, sudden death risk',
 '~0.4% adolescents',
 'Often early-onset; many transition to other substances',
 'Behavioral therapies, family involvement, treat neuropsychiatric sequelae',
 ARRAY['Other substance use','Psychotic disorders','Conduct disorder'],
 ARRAY['Conduct disorder','Depression','Cognitive deficits'],
 ARRAY['Poverty','Peer use','Adolescence','Trauma'],
 'Most common in adolescents','Slight male predominance','—'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'caffeine-use-disorder', 'Caffeine-Related Disorders', 'F15.929', '6C48',
 'DSM-5-TR includes caffeine intoxication, caffeine withdrawal; problematic use is a condition for further study.',
 ARRAY['Restlessness','Nervousness','Insomnia','Tachycardia','GI disturbance','Withdrawal: headache, fatigue, dysphoria, irritability, difficulty concentrating'],
 'Withdrawal within 24h of cessation in habitual users',
 'Functional impact in occupational/social settings',
 'Withdrawal common in habitual users (~50%)',
 'Variable; withdrawal resolves in days',
 'Gradual reduction, CBT for sleep, hydration, education',
 ARRAY['Anxiety disorders','Hyperthyroidism','Cardiac arrhythmias'],
 ARRAY['Anxiety','Insomnia'],
 ARRAY['High daily intake','Medical conditions'],
 'Can affect any age with chronic use','Equal across sexes','Caffeine norms vary widely'),

((SELECT id FROM dsm_chapters WHERE slug='substance'), 'gambling-disorder', 'Gambling Disorder', 'F63.0', '6C50',
 'Persistent and recurrent problematic gambling behavior leading to clinically significant impairment or distress.',
 ARRAY['Need to gamble with increasing amounts','Restless/irritable when cutting down','Repeated unsuccessful attempts to control gambling','Preoccupation','Gambling when distressed','Chasing losses','Lying about gambling','Jeopardizing relationships/jobs','Reliance on others for money'],
 '12-month period',
 'Financial, relational, occupational, and legal harm',
 '~0.2–0.6% past-year',
 'Chronic relapsing course',
 'CBT, motivational enhancement, Gamblers Anonymous, naltrexone, treat comorbid mood/SUD',
 ARRAY['Bipolar disorder mania','OCD','ASPD','Substance use'],
 ARRAY['Mood disorders','Substance use','Suicidality'],
 ARRAY['Early exposure','Family history','Mental illness'],
 'Onset adolescence to middle age','More common in males','Access influences prevalence'),

-- ============ CHAPTER 17: NEUROCOGNITIVE ============
((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'delirium', 'Delirium', 'F05', '6D70',
 'Acute disturbance in attention and awareness that develops over short period, fluctuates, and is caused by a medical condition, substance, or multiple etiologies.',
 ARRAY['Reduced attention and awareness','Acute onset hours-days','Fluctuating course','Additional cognitive disturbance (memory, language, perception)','Disorganized thinking','Altered consciousness','Sleep–wake cycle disruption','Psychomotor change'],
 'Hours to days; typically resolves with treatment of cause',
 'Increased morbidity, mortality, length of stay',
 '14–24% of hospital admissions; up to 80% ICU',
 'Resolves with cause treatment; may persist or recur',
 'Identify and treat underlying cause, supportive environment, reorientation, judicious antipsychotics for severe agitation',
 ARRAY['Major NCD','Psychotic disorders','Depression','Catatonia'],
 ARRAY['Dementia','Depression','Substance use'],
 ARRAY['Older age','Polypharmacy','Sensory impairment','Severe illness','Surgery'],
 'Most common in older adults','Equal across sexes','Cultural display of agitation varies'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'mild-ncd', 'Mild Neurocognitive Disorder', 'G31.84', '6D71',
 'Modest cognitive decline from previous level that does not interfere with independence in everyday activities.',
 ARRAY['Mild decline in attention, executive function, learning, memory, language, perceptual-motor, or social cognition','Reported by individual/informant','Documented on neuropsychological testing','Preserved instrumental activities'],
 'Persistent decline',
 'Greater effort/compensation required',
 '2–10% age 65; 5–25% age 85',
 'Variable; many remain stable, some progress to major NCD',
 'Cognitive training, treat reversible causes, address vascular risk, monitor over time',
 ARRAY['Normal aging','Major NCD','Depression (pseudodementia)','Delirium'],
 ARRAY['Depression','Anxiety','Sleep disorders'],
 ARRAY['Age','Vascular disease','APOE4','Head injury'],
 'Onset usually later life','Slight female predominance','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'vascular-ncd', 'Major or Mild Vascular Neurocognitive Disorder', 'F01.x', '6D81.0',
 'Cognitive decline temporally related to one or more cerebrovascular events, or evidence of decline prominently in attention/executive function.',
 ARRAY['Stepwise decline','Executive dysfunction','Slowed processing','Focal neurologic signs','Gait disturbance','Imaging evidence of cerebrovascular disease'],
 'Persistent',
 'Major impact on independence',
 '~15% of dementia cases',
 'Stepwise or progressive course',
 'Aggressive vascular risk reduction, antiplatelets, treat depression, rehabilitation',
 ARRAY['Alzheimer''s disease','Mixed dementia','Frontotemporal dementia','Depression'],
 ARRAY['Depression','Stroke sequelae','CV disease'],
 ARRAY['HTN','Diabetes','Smoking','Atrial fibrillation','Hyperlipidemia'],
 'Older adults','Slightly more common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'frontotemporal-ncd', 'Major or Mild Frontotemporal Neurocognitive Disorder', 'G31.09', '6D83',
 'Insidious onset and gradual progression with behavioral disinhibition or progressive language impairment.',
 ARRAY['Behavioral variant: disinhibition, apathy, loss of empathy, perseverative behavior, hyperorality','Primary progressive aphasia: nonfluent, semantic, logopenic variants','Early executive dysfunction','Preserved memory early'],
 'Progressive',
 'Severe psychosocial impact, often early',
 '~3–26 per 100,000 (younger-onset dementia)',
 'Progressive over 6–11 years',
 'Behavioral management, SSRIs for behavior, speech therapy, caregiver support',
 ARRAY['Alzheimer''s disease','Lewy body','Primary psychiatric disorder','Vascular dementia'],
 ARRAY['ALS','Parkinsonism','Depression'],
 ARRAY['Family history (MAPT, GRN, C9orf72)','TBI'],
 'Often onset 45–65','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'lewy-body-ncd', 'Major or Mild Lewy Body Neurocognitive Disorder', 'G31.83', '6D82',
 'Insidious onset and gradual progression with core features of fluctuating cognition, recurrent visual hallucinations, REM sleep behavior disorder, and spontaneous parkinsonism.',
 ARRAY['Fluctuating cognition','Visual hallucinations','REM sleep behavior disorder','Parkinsonism','Severe neuroleptic sensitivity','Autonomic dysfunction'],
 'Progressive',
 'Falls, hallucinations, caregiver burden',
 '~5% of dementia',
 'Progressive over 5–8 years',
 'Cholinesterase inhibitors, melatonin/clonazepam for RBD, avoid typical antipsychotics, treat parkinsonism cautiously',
 ARRAY['Alzheimer''s','Parkinson disease dementia','Delirium','Vascular dementia'],
 ARRAY['Parkinsonism','Depression','Autonomic failure'],
 ARRAY['Older age','Male sex','Family history'],
 'Onset >50','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'parkinsons-ncd', 'Major or Mild NCD due to Parkinson''s Disease', 'G20', '6D85.0',
 'Cognitive decline that begins in the context of established Parkinson''s disease.',
 ARRAY['Executive dysfunction','Visuospatial impairment','Bradyphrenia','Memory retrieval problems','Motor parkinsonism preceding cognitive decline'],
 'Insidious; emerges after parkinsonism',
 'Functional impairment beyond motor symptoms',
 'Up to 75% of PD develop dementia',
 'Progressive',
 'Cholinesterase inhibitors, optimize PD treatment, treat depression, caregiver support',
 ARRAY['Lewy body dementia','Alzheimer''s','Vascular dementia','Depression'],
 ARRAY['Depression','Anxiety','Psychosis'],
 ARRAY['Older age','Severe motor symptoms','Visual hallucinations on dopamine therapy'],
 'Late in PD course','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'huntington-ncd', 'Major or Mild NCD due to Huntington''s Disease', 'G10', '6D85.1',
 'Cognitive decline in the context of confirmed/suspected Huntington''s disease (genetic testing or family history).',
 ARRAY['Executive dysfunction','Slowed processing','Motor chorea','Personality and behavior changes','Psychiatric symptoms','Eventually global cognitive decline'],
 'Insidious; progressive',
 'Profound motor, cognitive, and behavioral impairment',
 '~3–10 per 100,000',
 'Progressive over 10–20 years',
 'Symptomatic chorea treatment, antidepressants, antipsychotics for behavior, genetic counseling, MDT care',
 ARRAY['Other movement disorders','Wilson disease','Tardive dyskinesia'],
 ARRAY['Depression','Anxiety','Psychosis','OCD'],
 ARRAY['HTT gene mutation','Family history'],
 'Onset usually 30s–40s','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'tbi-ncd', 'Major or Mild NCD due to Traumatic Brain Injury', 'F02.8', '6D84.0',
 'Cognitive decline temporally related to a TBI with documented loss of consciousness, posttraumatic amnesia, disorientation, or neurologic signs.',
 ARRAY['Memory deficits','Attention and executive dysfunction','Headache','Irritability','Light/noise sensitivity','Personality change','Sleep disturbance'],
 'Persists ≥1 week post-injury',
 'Variable; can be severe',
 '~1.7 million TBIs/year in US',
 'Most improve over months; severe TBI may have persistent deficits',
 'Cognitive rehabilitation, treat sleep/mood, gradual return to activity, family education',
 ARRAY['Postconcussion symptoms','Depression','PTSD','Other NCDs'],
 ARRAY['PTSD','Depression','Substance use'],
 ARRAY['Falls','MVA','Sports','Combat'],
 'Any age','More common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='neurocognitive'), 'hiv-ncd', 'Major or Mild NCD due to HIV Infection', 'F02.8', '6D85.2',
 'Cognitive impairment in HIV-positive individuals, with HIV infection as the likely etiology.',
 ARRAY['Slowed processing','Memory retrieval problems','Executive dysfunction','Apathy','Motor slowing','Subcortical pattern'],
 'Progressive without antiretroviral therapy',
 'Variable; ART reduces severity',
 '15–55% HIV-positive patients (variable)',
 'Improves with virologic control; may persist',
 'Antiretroviral therapy, cognitive rehab, treat comorbid depression/substance use',
 ARRAY['Opportunistic infections','Substance use','Depression','Other NCDs'],
 ARRAY['Depression','Substance use','PTSD'],
 ARRAY['Untreated HIV','Low CD4','Substance use'],
 'Any age post-infection','Equal across sexes','—'),

-- ============ CHAPTER 18: PERSONALITY ============
((SELECT id FROM dsm_chapters WHERE slug='personality'), 'paranoid-personality-disorder', 'Paranoid Personality Disorder', 'F60.0', '6D11',
 'Pervasive distrust and suspiciousness of others such that their motives are interpreted as malevolent.',
 ARRAY['Suspects exploitation/harm','Unjustified doubts about loyalty','Reluctant to confide','Reads hidden meanings into events','Bears persistent grudges','Perceives attacks not apparent to others','Recurrent suspicions of partner''s fidelity'],
 'Onset by early adulthood; persistent',
 'Impaired relationships and work',
 '~2.3% lifetime',
 'Chronic; some attenuation with age',
 'Long-term psychotherapy emphasizing alliance, CBT, treat comorbid conditions',
 ARRAY['Delusional disorder','Schizophrenia','PTSD','Other PDs'],
 ARRAY['Depression','Anxiety','Substance use'],
 ARRAY['Family history of psychotic disorders','Childhood trauma'],
 'Onset by early adulthood','More common in males','Caution with marginalized groups where mistrust may be adaptive'),

((SELECT id FROM dsm_chapters WHERE slug='personality'), 'schizoid-personality-disorder', 'Schizoid Personality Disorder', 'F60.1', '6D11',
 'Pervasive pattern of detachment from social relationships and restricted range of emotional expression.',
 ARRAY['Lacks desire for close relationships','Prefers solitary activities','Little interest in sex','Few pleasures','Few close friends','Indifferent to praise/criticism','Emotional coldness'],
 'Onset by early adulthood; persistent',
 'Limited relationships and occupational range',
 '~3.1% lifetime',
 'Stable trait pattern',
 'Long-term psychotherapy, gradual interpersonal skills building, treat comorbid depression',
 ARRAY['Schizotypal','Avoidant PD','ASD'],
 ARRAY['Depression','Anxiety'],
 ARRAY['Family history of schizophrenia'],
 'Onset by early adulthood','Slightly more common in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='personality'), 'schizotypal-personality-disorder', 'Schizotypal Personality Disorder', 'F21', '6D11',
 'Pervasive social and interpersonal deficits with cognitive/perceptual distortions and eccentric behavior.',
 ARRAY['Ideas of reference','Odd beliefs/magical thinking','Unusual perceptual experiences','Odd thinking/speech','Suspiciousness','Inappropriate or constricted affect','Eccentric appearance','Few close friends','Social anxiety not diminishing with familiarity'],
 'Onset by early adulthood; persistent',
 'Significant interpersonal and occupational impairment',
 '~3.9% lifetime',
 'Stable; small subset converts to schizophrenia',
 'Supportive psychotherapy, social skills training, low-dose antipsychotics for severe cognitive-perceptual symptoms',
 ARRAY['Schizophrenia','Schizoid','Avoidant','ASD'],
 ARRAY['Major depression','Anxiety','Substance use'],
 ARRAY['Family history of schizophrenia','Childhood adversity'],
 'Onset by early adulthood','Slightly more common in males','Culturally sanctioned beliefs must be distinguished'),

((SELECT id FROM dsm_chapters WHERE slug='personality'), 'histrionic-personality-disorder', 'Histrionic Personality Disorder', 'F60.4', '6D11',
 'Pervasive pattern of excessive emotionality and attention seeking.',
 ARRAY['Uncomfortable when not the center of attention','Inappropriately sexual/seductive','Rapidly shifting/shallow emotions','Uses physical appearance for attention','Impressionistic speech','Theatrical, exaggerated emotion','Suggestible','Considers relationships more intimate than they are'],
 'Onset by early adulthood; persistent',
 'Relationship instability and occupational impact',
 '~1.8% lifetime',
 'Stable; can attenuate with age',
 'Psychodynamic and cognitive therapies, treat comorbid mood disorders',
 ARRAY['Borderline PD','Narcissistic PD','Dependent PD'],
 ARRAY['Depression','Somatic symptom disorder','Substance use'],
 ARRAY['Family history of personality disorder','Childhood reinforcement of attention-seeking'],
 'Onset by early adulthood','Diagnosed more in females (controversial)','Gender norms heavily influence diagnosis'),

((SELECT id FROM dsm_chapters WHERE slug='personality'), 'avoidant-personality-disorder', 'Avoidant Personality Disorder', 'F60.6', '6D11',
 'Pervasive pattern of social inhibition, feelings of inadequacy, and hypersensitivity to negative evaluation.',
 ARRAY['Avoids occupational activities involving interpersonal contact','Unwilling to engage unless certain of being liked','Restraint within intimate relationships','Preoccupied with being criticized/rejected','Inhibited in new interpersonal situations','Views self as inept/inferior','Reluctant to take risks'],
 'Onset by early adulthood; persistent',
 'Significant occupational and social impairment',
 '~2.4% lifetime',
 'Chronic; significant overlap with social anxiety disorder',
 'CBT, social skills training, schema therapy, SSRIs',
 ARRAY['Social anxiety disorder','Dependent PD','Schizoid','ASD'],
 ARRAY['Depression','Anxiety','Substance use'],
 ARRAY['Behavioral inhibition','Childhood rejection','Trauma'],
 'Onset by early adulthood','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='personality'), 'dependent-personality-disorder', 'Dependent Personality Disorder', 'F60.7', '6D11',
 'Pervasive and excessive need to be taken care of leading to submissive/clinging behavior and fears of separation.',
 ARRAY['Difficulty making everyday decisions','Needs others to assume responsibility','Difficulty disagreeing','Difficulty initiating projects','Excessive lengths to obtain support','Discomfort/helplessness when alone','Urgently seeks another relationship when one ends','Preoccupied with fears of being left alone'],
 'Onset by early adulthood; persistent',
 'Restricted occupational range, vulnerability to abusive relationships',
 '~0.5–0.6%',
 'Chronic',
 'CBT for autonomy, assertiveness training, address comorbid mood/anxiety',
 ARRAY['Borderline PD','Histrionic','Avoidant'],
 ARRAY['Depression','Anxiety','Adjustment disorder'],
 ARRAY['Childhood chronic illness','Authoritarian parenting','Cultural context'],
 'Onset by early adulthood','Slightly more in females','Cultural norms about dependence vary'),

((SELECT id FROM dsm_chapters WHERE slug='personality'), 'obsessive-compulsive-personality-disorder', 'Obsessive-Compulsive Personality Disorder', 'F60.5', '6D11',
 'Pervasive pattern of preoccupation with orderliness, perfectionism, and mental and interpersonal control at the expense of flexibility.',
 ARRAY['Preoccupation with details/rules','Perfectionism interfering with completion','Excessive devotion to work','Overconscientious about morality','Inability to discard worthless objects','Reluctance to delegate','Miserly spending style','Rigidity and stubbornness'],
 'Onset by early adulthood; persistent',
 'Interpersonal conflict, decreased efficiency despite effort',
 '~2.1–7.9% lifetime',
 'Chronic; some compensation in structured roles',
 'CBT, schema therapy, stress reduction, address perfectionism',
 ARRAY['OCD','Hoarding disorder','Other PDs'],
 ARRAY['Depression','Anxiety','Eating disorders'],
 ARRAY['Family history','Authoritarian upbringing'],
 'Onset by early adulthood','More common in males','—'),

-- ============ CHAPTER 19: PARAPHILIC ============
((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'voyeuristic-disorder', 'Voyeuristic Disorder', 'F65.3', '6D30',
 'Recurrent sexual arousal from observing an unsuspecting person who is naked, disrobing, or engaging in sexual activity, acted on with nonconsenting person or causing distress/impairment.',
 ARRAY['Recurrent voyeuristic urges/fantasies/behavior','Acted on with non-consenting person','Distress/impairment'],
 'At least 6 months; minimum age 18 for diagnosis',
 'Legal consequences, relationship impact',
 '~12% men, 4% women',
 'Chronic',
 'CBT, relapse prevention, group therapy, address comorbidities, antiandrogens in severe cases',
 ARRAY['Conduct disorder','Substance intoxication','Hypersexual behaviors','ASPD'],
 ARRAY['Other paraphilic disorders','Substance use'],
 ARRAY['Childhood abuse','Other paraphilias'],
 'Minimum age 18 for diagnosis','Predominantly male','—'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'exhibitionistic-disorder', 'Exhibitionistic Disorder', 'F65.2', '6D31',
 'Recurrent sexual arousal from exposing one''s genitals to an unsuspecting person, acted on or causing distress/impairment.',
 ARRAY['Urges to expose genitals','Acted on with non-consenting person','Distress'],
 'At least 6 months',
 'Legal/social consequences',
 '2–4% males',
 'Chronic without treatment',
 'CBT, relapse prevention, antiandrogens in severe cases, sex-offender programs',
 ARRAY['ASPD','Substance intoxication','Mania','Frontal lobe injury'],
 ARRAY['Other paraphilic disorders','Substance use'],
 ARRAY['Childhood trauma','Other paraphilias'],
 'Onset typically adolescence/early adulthood','Predominantly male','—'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'frotteuristic-disorder', 'Frotteuristic Disorder', 'F65.81', '6D32',
 'Recurrent sexual arousal from touching/rubbing against a non-consenting person, acted on or causing distress/impairment.',
 ARRAY['Frotteuristic urges/behavior','Acted on with non-consenting person','Distress'],
 'At least 6 months',
 'Legal/social consequences',
 '~10% adult males admit to frotteurism',
 'Chronic',
 'CBT, relapse prevention, antiandrogens if needed',
 ARRAY['ASPD','Substance intoxication','Mania'],
 ARRAY['Other paraphilias','Substance use'],
 ARRAY['Childhood trauma','Other paraphilias'],
 'Onset adolescence/early adulthood','Predominantly male','—'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'sexual-masochism-disorder', 'Sexual Masochism Disorder', 'F65.51', '6D33',
 'Recurrent sexual arousal from being humiliated, beaten, bound, or made to suffer, causing distress/impairment.',
 ARRAY['Masochistic urges/fantasies/behavior','Personal distress','Functional impairment'],
 'At least 6 months',
 'Variable; sometimes injury or asphyxiation risk',
 'Unknown; <2.2% community endorsement of frequent practices',
 'Chronic',
 'Safety planning, CBT, treat comorbidities, consensual relationship work',
 ARRAY['Consensual BDSM without distress','Self-injury','Depression'],
 ARRAY['Other paraphilias','Depression','Substance use'],
 ARRAY['Childhood trauma','Other paraphilias'],
 'Onset typically adolescence/early adulthood','Reported across genders','Stigma affects help-seeking'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'sexual-sadism-disorder', 'Sexual Sadism Disorder', 'F65.52', '6D34',
 'Recurrent sexual arousal from physical or psychological suffering of another, acted on with non-consenting person or causing distress/impairment.',
 ARRAY['Sadistic urges/behavior','Acted on with non-consenting','Distress/impairment'],
 'At least 6 months',
 'Severe legal/safety consequences',
 '<2–3% community endorsement',
 'Chronic',
 'Specialized forensic treatment, CBT, antiandrogens in severe cases',
 ARRAY['Consensual BDSM','ASPD','Sexual sadism in serial offending'],
 ARRAY['ASPD','Other paraphilias'],
 ARRAY['Childhood trauma','Conduct disorder'],
 'Onset early adulthood','Predominantly male','—'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'pedophilic-disorder', 'Pedophilic Disorder', 'F65.4', '6D35',
 'Recurrent sexual arousal involving prepubescent children (generally age 13 or younger), acted on or causing significant distress/impairment.',
 ARRAY['Sexual urges/fantasies involving prepubertal children','Acted on or marked distress','Individual at least 16 and ≥5 years older than child'],
 'At least 6 months',
 'Severe legal, ethical, and victim consequences',
 '3–5% males (any attraction); much lower for disorder',
 'Chronic; high recidivism without intervention',
 'Specialized treatment programs (CBT, relapse prevention), antiandrogens, intensive monitoring',
 ARRAY['ASPD','Substance use','Cognitive impairment','OCD intrusive thoughts'],
 ARRAY['ASPD','Substance use','Mood disorders'],
 ARRAY['Childhood sexual abuse','Other paraphilias'],
 'Minimum age 16 for diagnosis','Overwhelmingly male','—'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'fetishistic-disorder', 'Fetishistic Disorder', 'F65.0', '6D36',
 'Recurrent sexual arousal from use of nonliving objects or highly specific focus on non-genital body parts, causing distress/impairment.',
 ARRAY['Fetishistic urges/behavior','Distress or impairment','Not limited to clothing used in cross-dressing or sex toys designed for genital stimulation'],
 'At least 6 months',
 'Relationship and occupational impact',
 'Unknown',
 'Chronic',
 'CBT, address relationship distress, accept variation without distress when not harmful',
 ARRAY['Transvestic disorder','Other paraphilias','OCD'],
 ARRAY['Anxiety','Depression'],
 ARRAY['Early conditioning','Other paraphilias'],
 'Onset typically adolescence','Predominantly male','—'),

((SELECT id FROM dsm_chapters WHERE slug='paraphilic'), 'transvestic-disorder', 'Transvestic Disorder', 'F65.1', '6D37',
 'Recurrent sexual arousal from cross-dressing, causing clinically significant distress/impairment.',
 ARRAY['Cross-dressing producing arousal','Distress or impairment','May specify with fetishism or autogynephilia'],
 'At least 6 months',
 'Relationship and occupational impact',
 'Unknown; <3% males',
 'Chronic',
 'CBT, couples therapy, distinguish from gender dysphoria',
 ARRAY['Gender dysphoria','Fetishistic disorder','Cross-dressing without distress'],
 ARRAY['Depression','Anxiety'],
 ARRAY['Conditioning','Other paraphilias'],
 'Onset typically adolescence','Predominantly heterosexual males','Cultural norms shape distress'),

-- ============ CHAPTER 20: OTHER ============
((SELECT id FROM dsm_chapters WHERE slug='other'), 'tardive-dyskinesia', 'Tardive Dyskinesia (Medication-Induced Movement Disorder)', 'G24.01', '8A02.13',
 'Involuntary athetoid or choreiform movements, typically of orofacial region, developing in association with neuroleptic or other dopamine-blocking medication use.',
 ARRAY['Orofacial dyskinesia (lip smacking, tongue movements)','Choreiform limb movements','Truncal movements','Often persists after medication discontinuation'],
 'Develops after months to years of medication exposure',
 'Social embarrassment, functional impact',
 '~20–30% with first-gen antipsychotics; lower with newer agents',
 'Often persistent; may improve with discontinuation',
 'VMAT2 inhibitors (valbenazine, deutetrabenazine), minimize antipsychotic exposure, switch to lower-risk agents',
 ARRAY['Stereotypies','Tics','Huntington''s disease','Spontaneous dyskinesia'],
 ARRAY['Schizophrenia','Mood disorders'],
 ARRAY['Older age','Female sex','Duration of antipsychotic use','Mood disorder'],
 'Higher in older adults','More common in females','—'),

((SELECT id FROM dsm_chapters WHERE slug='other'), 'neuroleptic-malignant-syndrome', 'Neuroleptic Malignant Syndrome', 'G21.0', '8A02.10',
 'Life-threatening reaction to dopamine-blocking medications characterized by hyperthermia, rigidity, autonomic instability, and altered mental status.',
 ARRAY['Hyperthermia','Lead-pipe rigidity','Autonomic instability (BP, HR)','Altered consciousness','Elevated CK','Diaphoresis','Mutism','Tremor'],
 'Onset hours to days after exposure',
 'Medical emergency with mortality risk',
 '0.01–0.02% per antipsychotic exposure',
 'Resolves over 1–2 weeks with treatment',
 'Stop offending agent, supportive care (cooling, hydration), dantrolene, bromocriptine, ICU monitoring',
 ARRAY['Serotonin syndrome','Malignant catatonia','Heat stroke','Anticholinergic toxicity'],
 ARRAY['Schizophrenia','Mood disorders','Substance use'],
 ARRAY['Dehydration','High-potency antipsychotics','Rapid dose escalation','Restraint'],
 'Any age','Slightly more in males','—'),

((SELECT id FROM dsm_chapters WHERE slug='other'), 'medication-induced-akathisia', 'Medication-Induced Acute Akathisia', 'G21.1', '8A02.12',
 'Subjective restlessness and observable restless movements developing within weeks of starting or increasing a dopamine-blocking medication.',
 ARRAY['Inner restlessness','Inability to sit still','Pacing','Rocking','Shifting weight','Distress','Dysphoria'],
 'Within weeks of medication start/increase',
 'Increased suicidality risk, treatment nonadherence',
 'Up to 30% with first-generation antipsychotics',
 'Improves with dose reduction or treatment',
 'Reduce dose, beta-blockers (propranolol), benzodiazepines, switch antipsychotic',
 ARRAY['RLS','Anxiety','Agitated depression','Mania'],
 ARRAY['Schizophrenia','Mood disorders'],
 ARRAY['High-potency antipsychotics','Rapid titration'],
 'Any age','Equal across sexes','—'),

((SELECT id FROM dsm_chapters WHERE slug='other'), 'other-specified-mental-disorder', 'Other Specified Mental Disorder', 'F99', '6E60',
 'Symptoms characteristic of a mental disorder that cause clinically significant distress/impairment but do not meet full criteria for any disorder in a specific class; clinician specifies the reason.',
 ARRAY['Subthreshold symptom patterns','Atypical presentations','Symptoms across multiple classes'],
 'Variable',
 'Significant distress or impairment',
 'Common diagnosis in clinical practice',
 'Variable',
 'Tailored to presenting features',
 ARRAY['Specified disorders within each class','Adjustment disorders'],
 ARRAY['Variable'],
 ARRAY['Variable'],
 'Across the lifespan','Equal','—'),

((SELECT id FROM dsm_chapters WHERE slug='other'), 'unspecified-mental-disorder', 'Unspecified Mental Disorder', 'F99', '6E61',
 'Symptoms characteristic of a mental disorder causing distress/impairment but not meeting full criteria, where clinician chooses not to specify the reason (e.g., insufficient information).',
 ARRAY['Symptomatic but uncategorized presentation'],
 'Variable',
 'Significant distress or impairment',
 'Common in emergency/early evaluation contexts',
 'Variable; placeholder pending further assessment',
 'Further evaluation, address acute symptoms, refer for specialty care',
 ARRAY['All specified mental disorders'],
 ARRAY['Variable'],
 ARRAY['Variable'],
 'Across the lifespan','Equal','—')

ON CONFLICT (slug) DO NOTHING;
